CREATE DATABASE ConnectPlus


CREATE TABLE TipoContatos(
	Id_TipoContatos  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Identificador NVARCHAR(244) NOT NULL,
	Titulo NVARCHAR(100) NOT NULL
)

CREATE TABLE Contatos(
	Id_Contatos  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome NVARCHAR(100) NOT NULL,
	FormaDeContato NVARCHAR(244) NOT NULL,
	Imagem VARCHAR(100) NOT NULL,
	Id_TipoContatos UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContatos (Id_TipoContatos),
)
DROP DATABASE ConnectPlus

SELECT * FROM Contatos